In [2]:
import numpy as np

In [8]:
arr = [56, 67, 78, 89]

In [9]:
print(arr)

[56, 67, 78, 89]


In [10]:
print(type(arr))

<class 'list'>


In [11]:
np_arr = np.array(arr)

In [12]:
print(np_arr)

[56 67 78 89]


In [13]:
print(type(np_arr))

<class 'numpy.ndarray'>


In [15]:
l = range(500) 
%timeit [i**2 for i in l] 

89.1 µs ± 2.35 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [16]:
m = np.arange(500) 
%timeit m**2 

2.18 µs ± 75 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [20]:
ar1 = np.array([10, 11, 12, 13]) 
ar1

array([10, 11, 12, 13])

In [21]:
ar1.ndim

1

In [22]:
ar1.shape

(4,)

In [24]:
ar2 = np.array([[40, 11, 62], [53, 34, 85]])
ar2

array([[40, 11, 62],
       [53, 34, 85]])

In [25]:
ar2.ndim

2

In [26]:
ar2.shape

(2, 3)

In [28]:
ar3 = np.array([[[20, 13], [91, 25]], [[73, 49], [72, 35]]])
ar3

array([[[20, 13],
        [91, 25]],

       [[73, 49],
        [72, 35]]])

In [29]:
ar3.ndim

3

In [30]:
ar3.shape

(2, 2, 2)

In [31]:
l1 = [90, 87, 84]
l1

[90, 87, 84]

In [32]:
np.array(l1)

array([90, 87, 84])

In [33]:
mat1 = [[21, 34, 52], [67, 87, 45], [59, 91, 23]]
mat1

[[21, 34, 52], [67, 87, 45], [59, 91, 23]]

In [34]:
np.array(mat1)

array([[21, 34, 52],
       [67, 87, 45],
       [59, 91, 23]])

In [35]:
np.array(mat1).shape

(3, 3)

In [37]:
n1 = np.arange(5)
n1

array([0, 1, 2, 3, 4])

In [39]:
n2 = np.arange(5, 15, 3)
n2

array([ 5,  8, 11, 14])

In [41]:
n3 = np.linspace(5, 15, 7)
n3

array([ 5.        ,  6.66666667,  8.33333333, 10.        , 11.66666667,
       13.33333333, 15.        ])

In [43]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [45]:
n4 = np.zeros((3,2))
n4

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [47]:
n5 = np.ones((2,4))
n5

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [49]:
n5 = np.eye(4)
n5

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [51]:
n4 = np.eye(2,5)
n4

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.]])

In [52]:
n3 = np.diag([15, 23, 11, 2])
n3

array([[15,  0,  0,  0],
       [ 0, 23,  0,  0],
       [ 0,  0, 11,  0],
       [ 0,  0,  0,  2]])

In [53]:
np.diag(n3)

array([15, 23, 11,  2])

In [55]:
r1 = np.random.randint(35, 105, 10)
print(r1)

[ 94  59  38 101  46  92  45  62  57  71]


In [57]:
r2 = np.random.rand(5)
r2

array([0.18923458, 0.84684406, 0.61092742, 0.11444541, 0.80261826])

In [58]:
r3 = np.random.randn(20)
r3

array([-0.46730022, -0.40411637,  0.27564831,  0.1053977 , -0.22173296,
        0.29318022, -1.81910885,  0.46977903, -0.43762122, -0.09485338,
       -1.08865787,  0.08463156, -0.98936422,  1.50324135, -0.80329218,
       -2.91016368, -1.24438488, -1.67115797, -0.36507348,  0.41700811])

In [60]:
a1 = np.array([1, 42, 90])
a2 = a1
a2[0] = 45
print(a1)
print(a2)

[45 42 90]
[45 42 90]


In [3]:
arr1 = np.arange(10) 
print(arr1) 
print(arr1.shape) 

[0 1 2 3 4 5 6 7 8 9]
(10,)


In [4]:
arr2 = arr1.reshape(2,5) 
arr2 

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [7]:
m = np.array([[34, 65, 78], [18, 32, 95]]) 
print(m) 
print("Shape of array: {}".format(m.shape)) 

[[34 65 78]
 [18 32 95]]
Shape of array: (2, 3)


In [8]:
n = m.reshape(3, 2)
print(n)
print("Shape of array: {}".format(n.shape)) 

[[34 65]
 [78 18]
 [32 95]]
Shape of array: (3, 2)


In [9]:
m = np.array([[34, 65, 78], [18, 32, 95]]) 
print(m) 
print("Shape of array: {}".format(m.shape)) 

[[34 65 78]
 [18 32 95]]
Shape of array: (2, 3)


In [10]:
t = m.T
print(t)

[[34 18]
 [65 32]
 [78 95]]


In [11]:
m.ravel()

array([34, 65, 78, 18, 32, 95])

In [12]:
t.ravel()

array([34, 18, 65, 32, 78, 95])

In [13]:
m = np.array([[34, 65, 78], [18, 32, 95]]) 
n = np.sort(m, axis = 1)
n

array([[34, 65, 78],
       [18, 32, 95]])

In [14]:
m = np.array([[34, 65, 78], [18, 32, 95]]) 
m = np.append(m , [49, 51, 81])
m

array([34, 65, 78, 18, 32, 95, 49, 51, 81])

In [16]:
m = np.delete(m, 4)
m

array([34, 65, 78, 18, 95, 49, 51, 81])

In [23]:
arr = np.arange(4, 14) 
print(arr) 
print(arr[3]) 

[ 4  5  6  7  8  9 10 11 12 13]
7


In [24]:
arr = np.diag([4, 9, 16]) 
print(arr) 
print(arr[1, 2]) 

[[ 4  0  0]
 [ 0  9  0]
 [ 0  0 16]]
0


In [25]:
arr[1, 2] = 34
arr

array([[ 4,  0,  0],
       [ 0,  9, 34],
       [ 0,  0, 16]])

In [26]:
arr = np.arange(4,15) 
arr

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [27]:
arr[1:9:3]

array([ 5,  8, 11])

In [28]:
arr = np.arange(15)
arr[4:]

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [29]:
arr[7:] = 21
arr

array([ 0,  1,  2,  3,  4,  5,  6, 21, 21, 21, 21, 21, 21, 21, 21])

In [30]:
m = np.arange(8)
m

array([0, 1, 2, 3, 4, 5, 6, 7])

In [31]:
m[::-1]

array([7, 6, 5, 4, 3, 2, 1, 0])

In [32]:
arr[7:] = m[::-1]
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 6, 5, 4, 3, 2, 1, 0])

In [35]:
m = np.random.randint(1, 10, 8)
m

array([7, 9, 9, 3, 2, 8, 8, 2])

In [36]:
m[m % 2 == 0]

array([2, 8, 8, 2])

In [37]:
m[m % 2 == 0] = -1
m

array([ 7,  9,  9,  3, -1, -1, -1, -1])

In [39]:
n = np.arange(1, 51, 8)
n

array([ 1,  9, 17, 25, 33, 41, 49])

In [40]:
n[[3, 1, 5]]

array([25,  9, 41])

In [41]:
n[[1, 6]] = 82
n

array([ 1, 82, 17, 25, 33, 41, 82])

In [44]:
p = np.array([8, 7, 6, 2])
print(p)
print(p+11)

[8 7 6 2]
[19 18 17 13]


In [45]:
p * 2

array([16, 14, 12,  4])

In [49]:
m = np.ones(4) + 2
m

array([3., 3., 3., 3.])

In [50]:
p - m

array([ 5.,  4.,  3., -1.])

In [51]:
p * m

array([24., 21., 18.,  6.])

In [53]:
x = np.array([[1,3], [3,5], [1,1]]) 
y = np.array([[3,5], [2,2], [2,4]])
x + y

array([[4, 8],
       [5, 7],
       [3, 5]])

In [54]:
x * y

array([[ 3, 15],
       [ 6, 10],
       [ 2,  4]])

In [55]:
z = np.diag([4, 5, 9])
z

array([[4, 0, 0],
       [0, 5, 0],
       [0, 0, 9]])

In [56]:
m = np.array([[3,2,2],[1,4,2],[4,1,6]]) 
n = np.array([[4,5,1], [0,4,3], [8,2,1]]) 
m * n

array([[12, 10,  2],
       [ 0, 16,  6],
       [32,  2,  6]])

In [59]:
m = np.array([[3,2,2],[1,4,2],[4,1,6]]) 
n = np.array([[4,5,1], [0,4,3], [8,2,1]]) 
o = np.array([[3,2,2],[1,4,2],[4,1,6]])  

In [60]:
np.array_equal(m, n)

False

In [61]:
np.array_equal(m, o)

True

In [62]:
a1 = np.array([0,1,0,1], dtype = bool)
a2 = np.array([1,1,1,0], dtype = bool)
np.logical_or(a1, a2)

array([ True,  True,  True,  True])

In [63]:
np.logical_and(a1, a2)

array([False,  True, False, False])

In [68]:
op = np.arange(1, 6)
np.sin(op)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427])

In [69]:
np.log(op)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [70]:
np.exp(op)

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])

In [73]:
m = np.arange(5)
m + np.array([3,2])

ValueError: operands could not be broadcast together with shapes (5,) (2,) 

In [74]:
p = np.array([8, 7, 6, 2])

In [75]:
np.sum(p)

23

In [76]:
p = np.array([[9,8], [2,7]])
p

array([[9, 8],
       [2, 7]])

In [77]:
p.sum(axis=0)

array([11, 15])

In [78]:
p.sum(axis=1)

array([17,  9])

In [79]:
p = np.array([8, 7, 6, 2])

In [80]:
p.min()

2

In [81]:
p.max()

8

In [82]:
p.argmin()

3

In [83]:
p.argmax()

0

In [84]:
narr = np.arange(1, 18, 2)
print('Array:', format (narr)) 
print('Min element:', np.min(narr)) 
print('Max element:',np.max(narr)) 
print('Sum of elements: ', np. sum(narr)) 
print('Mean of elements:', np.mean (narr)) 
print('Median of elements:', np.median (narr)) 
print('Standard deviation of elements:', np.std (narr)) 

Array: [ 1  3  5  7  9 11 13 15 17]
Min element: 1
Max element: 17
Sum of elements:  81
Mean of elements: 9.0
Median of elements: 9.0
Standard deviation of elements: 5.163977794943222
